clone:
  depth: full
  
pipelines:
  default:
    - step:
        name: Deploy
        image: python:3.6.5
        deployment: staging
        caches:
          - pip
        script:
          - pip install --upgrade pip
          - pip install -r requirements.txt --no-input
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD